name: file_based_mustache
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Adam Stark<llamadonica@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  mustache: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
