name: file_based_mustache
description: A library that builds file trees based on a mustache-like template.
version: 0.0.2
author: Adam Stark<llamadonica@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  mustache: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
